#[default_session]
#startup_command = "gcloud config configurations activate default && prompt_dir"
startup_command = "ls"

[[session]]
name = "Downloads ğŸ“¥"
path = "~/Downloads"
startup_command = "ls"

[[session]]
name = "tmux config ğŸ› ï¸"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"

[[session]]
name = "Sesh ğŸŒŠ"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "Alacritty ğŸ–¥ï¸"
path = "~/.config/alacritty"
startup_command = "nvim alacritty.toml"

[[session]]
name = "Notes ğŸ“"
path = "~/Notes"
startup_command = "nvim Board.md"

[[session]]
name = ".dotfiles ğŸ“‚"
path = "~/.dot_files"
startup_command = "nvim .zshrc"

[[session]]
name = "BillingService ğŸš€"
path = "~/DT/billing-service"
startup_command = "nvim ."

[[session]]
name = "RMA ğŸ‘¨â€ğŸ”§"
path = "~/DT/billing-service/cmd/rma"
startup_command = "clear && cat README.md"

[[session]]
name = "NeoVim "
path = "~/.config/nvim"
startup_command = "nvim init.lua"

[[session]]
name = "OnCall"
path = "~/OnCall"
startup_command = "gcloud config configurations activate oncall && prompt_dir"


